import { chromium } from "@playwright/test";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const targetDir = resolve("privacy-reconstruction/round-01");
const browser = await chromium.launch({ headless: true });

try {
  // 1. Primary Baseline: 1024x1536 viewport, DPR 1
  const page = await browser.newPage({
    viewport: { width: 1024, height: 1536 },
    deviceScaleFactor: 1,
    reducedMotion: "reduce",
  });

  const errors = [];
  page.on("pageerror", (err) => errors.push(err.message));

  console.log("Navigating to http://127.0.0.1:3210/privacy...");
  await page.goto("http://127.0.0.1:3210/privacy", { waitUntil: "domcontentloaded" });
  await page.waitForSelector(".privacy-hero");
  await page.waitForTimeout(1200);

  await page.evaluate(async () => {
    await document.fonts.ready;
    await Promise.all(
      [...document.images].map((img) => img.decode().catch(() => {}))
    );
  });

  // Full page screenshot
  await page.screenshot({
    path: `${targetDir}/candidate.png`,
    fullPage: true,
    scale: "css",
    animations: "disabled",
  });
  console.log("Saved fullPage candidate.png");

  // Viewport screenshot 1024x1536
  await page.screenshot({
    path: `${targetDir}/candidate-1024x1536.png`,
    fullPage: false,
    scale: "css",
    animations: "disabled",
  });
  console.log("Saved candidate-1024x1536.png");

  // Evaluate collect.js generated by draw-ui prepare_capture
  const collectScript = await readFile(`${targetDir}/collect.js`, "utf8");
  const captureData = await page.evaluate(collectScript);
  captureData.full_page = true;
  captureData.screenshot_scale = "css";

  await writeFile(
    `${targetDir}/capture.json`,
    JSON.stringify(captureData, null, 2),
    "utf8"
  );
  console.log("Saved capture.json");

  // 2. Responsive Viewports Check (1280, 1440, 390)
  for (const vp of [
    { name: "desktop-1280", width: 1280, height: 900 },
    { name: "desktop-1440", width: 1440, height: 900 },
    { name: "mobile-390", width: 390, height: 844 },
  ]) {
    await page.setViewportSize({ width: vp.width, height: vp.height });
    await page.waitForTimeout(400);
    const scrollWidth = await page.evaluate(() => document.documentElement.scrollWidth);
    const clientWidth = await page.evaluate(() => document.documentElement.clientWidth);
    const overflow = scrollWidth > clientWidth;
    console.log(`Responsive check [${vp.name}]: clientWidth=${clientWidth}, scrollWidth=${scrollWidth}, overflow=${overflow}`);
    await page.screenshot({
      path: `${targetDir}/candidate-${vp.name}.png`,
      fullPage: false,
      scale: "css",
    });
  }

  if (errors.length > 0) {
    console.error("Page errors detected:", errors);
  } else {
    console.log("Zero console/page errors detected.");
  }
} finally {
  await browser.close();
}
