// Generated by design/kids-closeout/scripts/prepare-webp.mjs.
export const kidsAssets: Record<string, { src: string; width: number; height: number }> = {
  hero: {
    src: "/kids-art/optimized/hero-hd-1080.28ace45bd77d.webp",
    width: 1080,
    height: 601,
  },
  logo: {
    src: "/kids-art/optimized/logo-hd-320.1f8361e2a219.webp",
    width: 320,
    height: 107,
  },
  "question-1": {
    src: "/kids-art/optimized/question-1.aa932d49de48.webp",
    width: 145,
    height: 64,
  },
  "question-3": {
    src: "/kids-art/optimized/question-3.cff4d793cb25.webp",
    width: 145,
    height: 64,
  },
  "question-5": {
    src: "/kids-art/optimized/question-5.3c7726740c90.webp",
    width: 146,
    height: 62,
  },
  "question-6": {
    src: "/kids-art/optimized/question-6.663c77ec24f8.webp",
    width: 145,
    height: 62,
  },
  "question-7": {
    src: "/kids-art/optimized/question-7.69abc9c21551.webp",
    width: 145,
    height: 64,
  },
  "question-8": {
    src: "/kids-art/optimized/question-8.501a6372043b.webp",
    width: 141,
    height: 65,
  },
  "use-classroom": {
    src: "/kids-art/optimized/use-classroom.3275006d071f.webp",
    width: 52,
    height: 49,
  },
  "use-road": {
    src: "/kids-art/optimized/use-road.70c6d0db76be.webp",
    width: 49,
    height: 49,
  },
  "use-dinner": {
    src: "/kids-art/optimized/use-dinner.ba89adb468e8.webp",
    width: 38,
    height: 49,
  },
  "uses-cloud": {
    src: "/kids-art/optimized/uses-cloud.202d0dd50a49.webp",
    width: 84,
    height: 60,
  },
  "browse-star": {
    src: "/kids-art/optimized/browse-star.c12edf0f0354.webp",
    width: 57,
    height: 43,
  },
  "browse-spark": {
    src: "/kids-art/optimized/browse-spark.c60c0dfe23d4.webp",
    width: 47,
    height: 43,
  },
  "related-funny": {
    src: "/kids-art/optimized/related-funny.d0a64c4bf012.webp",
    width: 97,
    height: 85,
  },
  "related-friends": {
    src: "/kids-art/optimized/related-friends.9372f533ccc1.webp",
    width: 97,
    height: 85,
  },
  "related-all": {
    src: "/kids-art/optimized/related-all.373a39a785c9.webp",
    width: 96,
    height: 85,
  },
  "closing-left": {
    src: "/kids-art/optimized/closing-left.8bf9827bbf41.webp",
    width: 223,
    height: 136,
  },
  "closing-right": {
    src: "/kids-art/optimized/closing-right.62cb40d57e41.webp",
    width: 215,
    height: 136,
  },
};
export const kidsHeroSrcSet =
  "/kids-art/optimized/hero-hd-480.adfd6f617b5e.webp 480w, /kids-art/optimized/hero-hd-768.2efd06640b26.webp 768w, /kids-art/optimized/hero-hd-1080.28ace45bd77d.webp 1080w, /kids-art/optimized/hero-hd-1480.9bc65f33790f.webp 1480w";
export const kidsLogoSrcSet =
  "/kids-art/optimized/logo-hd-256.7e77467d88de.webp 256w, /kids-art/optimized/logo-hd-320.1f8361e2a219.webp 320w, /kids-art/optimized/logo-hd-480.66f02a91910a.webp 480w";

export const kidsRetinaAssets: Record<string, string> = {
  "question-1": "/kids-art/optimized/question-1-2x.b8217669a518.webp",
  "question-3": "/kids-art/optimized/question-3-2x.0bd69f1d3e83.webp",
  "question-5": "/kids-art/optimized/question-5-2x.5db49b4a8cb4.webp",
  "question-6": "/kids-art/optimized/question-6-2x.f72d9d70595e.webp",
  "question-7": "/kids-art/optimized/question-7-2x.eb0188867184.webp",
  "question-8": "/kids-art/optimized/question-8-2x.9cab41da66d7.webp",
  "use-classroom": "/kids-art/optimized/use-classroom-2x.6109fa1b8001.webp",
  "use-road": "/kids-art/optimized/use-road-2x.c46aa776a894.webp",
  "use-dinner": "/kids-art/optimized/use-dinner-2x.af32798991fe.webp",
  "uses-cloud": "/kids-art/optimized/uses-cloud-2x.839588eec63e.webp",
  "browse-star": "/kids-art/optimized/browse-star-2x.1d7ca94057c1.webp",
  "browse-spark": "/kids-art/optimized/browse-spark-2x.c8726bd748a8.webp",
  "related-funny": "/kids-art/optimized/related-funny-2x.5d5f3b3f8789.webp",
  "related-friends": "/kids-art/optimized/related-friends-2x.9d1275e230e0.webp",
  "related-all": "/kids-art/optimized/related-all-2x.e87b6decc3b3.webp",
  "closing-left": "/kids-art/optimized/closing-left-2x.7896e3166309.webp",
  "closing-right": "/kids-art/optimized/closing-right-2x.b8e966b14cc3.webp",
};
