import { createRouteRegistry } from "@/platform/seo/route-registry";
import type { RouteDefinition } from "@/platform/seo/types";

import { seoConfig } from "./seo.config";

export const routeDefinitions = [
  {
    route: "/",
    class: "public_indexable",
    searchIntent:
      "browse, play, and discover Would You Rather questions for friends, kids, couples, and parties",
    primaryKeyword: "would you rather questions",
    secondaryKeywords: [
      "funny would you rather questions",
      "would you rather questions for kids",
      "hard would you rather questions",
    ],
    title: "Would You Rather Questions – Play Fun Questions Online",
    description:
      "Browse Would You Rather questions for kids, adults, couples, friends and parties. Pick A or B, play instantly, and find the perfect dilemma for any group.",
    h1: "Would You Rather Questions",
    pageType: "WebApplication",
    relatedRoutes: [
      "/would-you-rather-questions-for-kids",
      "/funny-would-you-rather-questions",
      "/hard-would-you-rather-questions",
      "/would-you-rather-questions-for-friends",
      "/would-you-rather-questions-for-couples",
    ],
    lastModified: "2026-09-29",
    reviewStatus: "reviewed",
    reviewFingerprint: "82443cae2c9a75367a00acf5fa3615c536f9e0e10eb21d578929e60ad9dc5691",
  },
  {
    route: "/would-you-rather-questions-for-kids",
    class: "public_indexable",
    searchIntent:
      "find clean, engaging Would You Rather questions suitable for kids and classrooms",
    primaryKeyword: "would you rather questions for kids",
    secondaryKeywords: [
      "fun questions for kids",
      "clean would you rather",
      "classroom icebreakers for students",
    ],
    title: "Would You Rather Questions for Kids – Fun & Clean Dilemmas",
    description:
      "Discover the best clean and imaginative Would You Rather questions for kids. Perfect for school classrooms, family road trips, and dinner conversations.",
    h1: "Would You Rather Questions for Kids",
    pageType: "Article",
    relatedRoutes: [
      "/",
      "/funny-would-you-rather-questions",
      "/would-you-rather-questions-for-friends",
    ],
    lastModified: "2026-09-29",
    reviewStatus: "reviewed",
    reviewFingerprint: "1b3c62995db5f268b77082ce6b4dca5e8346d26e10637f512c1eb025842c78d7",
  },
  {
    route: "/funny-would-you-rather-questions",
    class: "public_indexable",
    searchIntent: "browse hilarious and ridiculous Would You Rather questions for entertainment",
    primaryKeyword: "funny would you rather questions",
    secondaryKeywords: [
      "hilarious would you rather",
      "weird would you rather questions",
      "silly party questions",
    ],
    title: "Funny Would You Rather Questions – Hilarious & Absurd Scenarios",
    description:
      "Explore hilarious and absurd Would You Rather questions guaranteed to spark laughter at parties, road trips, and lively weekend get-togethers.",
    h1: "Funny Would You Rather Questions",
    pageType: "Article",
    relatedRoutes: [
      "/",
      "/hard-would-you-rather-questions",
      "/would-you-rather-questions-for-friends",
    ],
    lastModified: "2026-09-29",
    reviewStatus: "reviewed",
    reviewFingerprint: "960089f2b523e71bc8ef96ce4467088ac5c5ab34401783fec2156f9f6fb5956d",
  },
  {
    route: "/hard-would-you-rather-questions",
    class: "public_indexable",
    searchIntent:
      "find challenging, thought-provoking Would You Rather questions for deep discussions",
    primaryKeyword: "hard would you rather questions",
    secondaryKeywords: [
      "impossible would you rather",
      "tough moral questions",
      "deep dilemmas to debate",
    ],
    title: "Hard Would You Rather Questions – Impossible & Deep Dilemmas",
    description:
      "Tackle the toughest, mind-bending Would You Rather questions designed to spark fierce debates, moral dilemmas, and late-night philosophical discussions.",
    h1: "Hard Would You Rather Questions",
    pageType: "Article",
    relatedRoutes: [
      "/",
      "/funny-would-you-rather-questions",
      "/would-you-rather-questions-for-couples",
    ],
    lastModified: "2026-09-29",
    reviewStatus: "reviewed",
    reviewFingerprint: "000fe484e3473c838f082d8e7e061c88f4bac0f6cd78971f303ddacbf3077fcf",
  },
  {
    route: "/would-you-rather-questions-for-friends",
    class: "public_indexable",
    searchIntent: "discover fun and engaging Would You Rather questions to play with close friends",
    primaryKeyword: "would you rather questions for friends",
    secondaryKeywords: [
      "party questions for friends",
      "game night icebreakers",
      "questions to ask best friends",
    ],
    title: "Would You Rather Questions for Friends – Game Night Dilemmas",
    description:
      "Get your group laughing and arguing with these engaging Would You Rather questions made for best friends, weekend hangouts, and social game nights.",
    h1: "Would You Rather Questions for Friends",
    pageType: "Article",
    relatedRoutes: ["/", "/funny-would-you-rather-questions", "/hard-would-you-rather-questions"],
    lastModified: "2026-09-29",
    reviewStatus: "reviewed",
    reviewFingerprint: "d3ed99a7671ea59a186af0802263b0467705235a5c90f9310ca68ad2e405194a",
  },
  {
    route: "/would-you-rather-questions-for-couples",
    class: "public_indexable",
    searchIntent:
      "find romantic and thought-provoking Would You Rather questions for partners and couples",
    primaryKeyword: "would you rather questions for couples",
    secondaryKeywords: [
      "date night questions",
      "questions for relationships",
      "couples conversation starters",
    ],
    title: "Would You Rather Questions for Couples – Romantic Date Night",
    description:
      "Strengthen your bond and discover new sides of your partner with these curated Would You Rather questions for date nights, dinner, and road trips.",
    h1: "Would You Rather Questions for Couples",
    pageType: "Article",
    relatedRoutes: [
      "/",
      "/hard-would-you-rather-questions",
      "/would-you-rather-questions-for-friends",
    ],
    lastModified: "2026-09-29",
    reviewStatus: "reviewed",
    reviewFingerprint: "fc11b306cb9487acf532a5c20ec47758ad5cc25b7ee3d6781dca7eabf3f83760",
  },
  {
    route: "/privacy",
    class: "public_noindex",
    pageType: "Legal",
    title: "Privacy Notice",
    description: "Project-configured privacy notice.",
  },
  {
    route: "/terms",
    class: "public_noindex",
    pageType: "Legal",
    title: "Terms of Service",
    description: "Project-configured terms of service.",
  },
  {
    route: "/acceptable-use",
    class: "public_noindex",
    pageType: "Legal",
    title: "Acceptable Use Policy",
    description: "Project-configured acceptable use policy.",
  },
  {
    route: "/refund-policy",
    class: "public_noindex",
    pageType: "Legal",
    title: "Refund and Cancellation Policy",
    description: "Project-configured refund and cancellation policy.",
  },
  {
    route: "/contact",
    class: "public_noindex",
    pageType: "Legal",
    title: "Contact",
    description: "Project contact information.",
  },
  {
    route: "/account-deletion",
    class: "public_noindex",
    pageType: "Legal",
    title: "Account Deletion",
    description: "Account deletion instructions and lifecycle summary.",
  },
  { route: "/sign-in", class: "public_noindex" },
  { route: "/auth/magic-link/confirm", class: "public_noindex" },
  { route: "/account", class: "private" },
  { route: "/account/security", class: "private" },
  { route: "/account/billing", class: "private" },
  { route: "/account/credits", class: "private" },
  { route: "/account/deleted", class: "private" },
  { route: "/checkout/return", class: "private" },
  { route: "/robots.txt", class: "system" },
  { route: "/sitemap.xml", class: "system" },
  { route: "/api/auth", class: "system" },
  { route: "/api/auth/magic-link/request", class: "system" },
  { route: "/api/auth/magic-link/confirm", class: "system" },
  { route: "/api/account/delete", class: "system" },
  { route: "/api/commerce/checkout", class: "system" },
  { route: "/api/commerce/subscription/cancel", class: "system" },
  { route: "/api/commerce/subscription/resume", class: "system" },
  { route: "/api/commerce/refunds", class: "system" },
  { route: "/api/webhooks/waffo", class: "system" },
  { route: "/api/internal/jobs/account-deletion", class: "system" },
  { route: "/api/internal/jobs/commerce", class: "system" },
  { route: "/api/internal/jobs/credit-expiry", class: "system" },
  { route: "/api/internal/jobs/reconcile", class: "system" },
  { route: "/api/health/live", class: "system" },
  { route: "/api/health/ready", class: "system" },
  { route: "/api/test/emails/latest", class: "system" },
  { route: "/api/wyr/vote", class: "system" },
  { route: "/api/internal/seo/indexnow", class: "system" },
  { route: "/indexnow-key.txt", class: "system" },
] as const satisfies readonly RouteDefinition[];

export const routeRegistry = createRouteRegistry(seoConfig, routeDefinitions);
