import fs from "fs";
import path from "path";
import crypto from "crypto";

const appServerDir = path.resolve(process.cwd(), ".next/server/app");

if (!fs.existsSync(appServerDir)) {
  console.warn("Directory .next/server/app does not exist yet. Skipping hash extraction.");
  process.exit(0);
}

function scanHtmlFiles(dir: string): string[] {
  let files: string[] = [];
  for (const item of fs.readdirSync(dir)) {
    const full = path.join(dir, item);
    if (fs.statSync(full).isDirectory()) {
      files = files.concat(scanHtmlFiles(full));
    } else if (item.endsWith(".html")) {
      files.push(full);
    }
  }
  return files;
}

const htmlFiles = scanHtmlFiles(appServerDir);
const routeHashes: Record<string, string[]> = {};
const allHashes = new Set<string>();

for (const file of htmlFiles) {
  const relative = path.relative(appServerDir, file);
  // Normalize route name: "index.html" -> "/", "find-questions.html" -> "/find-questions"
  let route = "/" + relative.replace(/\.html$/, "").replace(/(?:^|\/)index$/, "");
  if (route === "") route = "/";

  const html = fs.readFileSync(file, "utf8");
  const inlines = [...html.matchAll(/<script(?![^>]*src=)[^>]*>([\s\S]*?)<\/script>/gi)];
  const pageHashes: string[] = [];

  for (const s of inlines) {
    const content = s[1];
    if (typeof content !== "string" || content.trim().length === 0) continue;
    const hash = crypto.createHash("sha256").update(content).digest("base64");
    pageHashes.push(hash);
    allHashes.add(hash);
  }

  routeHashes[route] = pageHashes;
}

const sortedAllHashes = [...allHashes].sort();

const outputPayload = {
  routes: routeHashes,
  all: sortedAllHashes,
};

const targetJsonPath = path.resolve(process.cwd(), ".next/static-inline-hashes.json");
fs.writeFileSync(targetJsonPath, JSON.stringify(outputPayload, null, 2) + "\n", "utf8");

const tsPath = path.resolve(process.cwd(), "src/platform/security/static-inline-hashes.ts");
const tsContent = `// This file is generated by scripts/generate-static-csp-hashes.ts
// DO NOT EDIT MANUALLY. Run "bun scripts/generate-static-csp-hashes.ts" to regenerate.

export const STATIC_INLINE_HASHES: readonly string[] = ${JSON.stringify(sortedAllHashes, null, 2)};
`;
fs.writeFileSync(tsPath, tsContent, "utf8");

console.log(
  `Successfully generated static inline CSP hashes for ${Object.keys(routeHashes).length} routes (total unique: ${sortedAllHashes.length}) to .next/static-inline-hashes.json and src/platform/security/static-inline-hashes.ts`,
);
